pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo "Building Docker Image..."
                sh 'docker build -t flask-deploy-app .'
            }
        }

        stage('Test') {
            steps {
                echo "Running Tests inside Docker..."
                sh 'docker run --rm flask-deploy-app pytest'
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying Container..."

                sh 'docker stop flask-container || true'
                sh 'docker rm flask-container || true'

                sh 'docker run -d -p 5000:5000 --name flask-container flask-deploy-app'
            }
        }
    }
}